### ISSUE TITLE
Moving [FilterEntity] Data Annotations to seperate nuget package

### ISSUE THREAD

**Issue by luzaq86** [fschick/FilterExpressionCreator#1]
Sharing ViewModels between API and Blazor Web Assembly project  is currently not possible, because  annotating classes with `[FilterEntity(Prefix = "")] `  requires a  `Schick.FilterExpressionCreator.Mvc` package which is not supported by the Blazor framework and end up with a cascade of errors.

Can the data annotation attributes be moved to a seperate lighweight package?

**Comment by fschick** [comment]
I'll will have a look at this tomorrow

**Comment by fschick** [comment]
Changed, abstractions moved to new package 'FS.FilterExpressionCreator.Abstractions'. See https://github.com/fschick/FilterExpressionCreator/releases/tag/3.1.0

**Comment by luzaq86** [comment]
Great stuff, thanks a lot for quick response! great package, the orderby and include statements would also be useful if you consider extending it further anytime in the future. Although I have written them myself, they have dependency in `System.Linq.Expressions`. 

Also, expression casting (mapping) can also be done using `AutoMapper.Extensions.ExpressionMapping` it provides more flexibility with mapping fields with different names, but by the cost of performance I guess.

Great job anyway.

**Comment by fschick** [comment]
I thought about sorting but omitted it for the first. I'm not sure if existing technologies like GraphQL or OData are a better alternative if you need full flexibility. 

What do you mean with 'include' exactly?

Where do you think AutoMapper could help? The performance is negligible. I assume that the following (db) query will take much more time than AutoMapper.

**Comment by luzaq86** [comment]
The Include query parameter to retrieve also child object elements in result. 

There is an extension package for `AutoMapper.Extensions.ExpressionMapping`. If your Dtos and ViewModels have different property names you can configure autommaper accordingly and use ExpressionMapper to map it.

 ```
   public class UserDto
    {
        public int UserId { get; set; }

    }

    public class UserViewModel
    {
        public int Id { get; set; }
    }

    public class UserProfile : Profile
    {
        public UserProfile()
        {
            CreateMap<UserDto, UserViewModel>()
                .ForMember(x => x.Id, opt => opt.MapFrom(y => y.UserId))
                .ReverseMap();
        }
    }
```

```
  public static class ExpressionExtensions
    {
        public static Expression<Func<TModel, bool>> ToDto<TModel, TViewModel>(
            this Expression<Func<TViewModel, bool>> filter, IMapper mapper)
        {
            return filter == null
                ? null
                : mapper.MapExpression<
                    Expression<Func<TViewModel, bool>>,
                    Expression<Func<TModel, bool>>>(filter);
        }

        public static Expression<Func<TModel, bool>> CreateFilterDto<TModel, TViewModel>(this EntityFilter<TViewModel> entityFilter, IMapper mapper) where TViewModel : class
        {
            return entityFilter.CreateFilter().ToDto<TModel, TViewModel>(mapper);
        }
    }
```

```
...
//usage
var filter1 = new EntityFilter<UserViewModel>();
filter.Add(x => x.Id, 1);
vat dtoFilter = filter.CreateFilterDto<UserDto, UserViewModel>();
```

**Comment by fschick** [comment]
AutoMapper looks fine. Extension method should always be able to add. Replacement of EntityFilter.Cast() with AutoMapper is more complex because the cast creates a modifiable/serializable copy of EntityFilter rather than an expression. I will check it next week.

Include would be a separate thing like sorting, currently I have no plan for this.
