### ISSUE TITLE
Inclusion of null check on nested collections causes conflict with Nhibernate

### ISSUE THREAD

**Issue by paul-aylett** [fschick/FilterExpressionCreator#11]
Hi,

I am working on a project using Nhibernate and have begun implementing Plainquire, I have found an issue though (which I think is perhaps an issue on both ends).

Nhibernate does not appear capable of handling null checks on collections of entities. It generates:
`(.is not null)` which is not valid SQL.

Plainquire however, does not appear to offer the ability to remove this null check, which I don't believe is necessary in other ORMs either (though may be wrong here).

https://github.com/plainquire/plainquire/blob/21f77c25ac3a3017885b8b031c494783c224264b/Plainquire.Filter/Plainquire.Filter/Filters/EntityFilter.cs#L468-L474

Would it be possible to offer some ability to remove this null check?

Kind regards,
Paul

**Comment by fschick** [comment]
IMHO, the null check is not necessary for SQL at all. But the library creates expressions and there is always a chance that the expression will be compiled and executed. That is why I added the null checks.

I think it would be useful to extend the configuration to be able to turn the null-checks off.

At first glance, I don't think the change is very complex. However, the tests need to be expanded to reflect the new switch.

Are you thinking about a pull request or would you wait the feature is implemented by me (I think 1-2 weeks, maybe faster)?

**Comment by paul-aylett** [comment]
Thanks for the fast reply. I would wait; I have already hacked my way around it in my project with an extension method off of EntityFilter to return the expression with null checks removed on any entity iEnumerables.
It turns out we have another issue in this area regarding nhibernate anyway so will revisit and update to your newly implemented way.

Thanks again

**Comment by fschick** [comment]
I added `FilterConfiguration.OmitPropertyNullChecks` to omit null checks for properties in filter expressions. You can provide configuration as described [here](https://github.com/plainquire/plainquire/tree/main-fs-conditional-null-checks?tab=readme-ov-file#configuration). I created a [pre-release 5.3.0-beta1](https://github.com/plainquire/plainquire/releases/tag/5.3.0-beta1) because I'm unable to test it with NHibernate. Could you test it?

If you like and are able to provide a minimal test case with an NHinbernate in-memory database, I will add it to the unit tests.

**Comment by paul-aylett** [comment]
Hey, thanks for this. I've tested the beta on my real world example and it's working well. If I get some time on the weekend I'll have a look at doing the in-memory example for you.

**Comment by fschick** [comment]
I optimized things further. I removed `FilterConfiguration.OmitPropertyNullChecks` in favor of `FilterConfiguration.UseConditionalAccess`. As long as you use the filters directly (`entity.Where(filter)`), no more configuration is required. Null-checks are now always omitted in case of expressions.

If the new behavior is not working out-of-the-box, use `FilterConfiguration.UseConditionalAccess = ConditionalAccess.Never`

Changes released with new [5.3.0-beta2](https://github.com/plainquire/plainquire/releases/tag/5.3.0-beta2)

**Comment by fschick** [comment]
Regarding unit tests: The underlying database doesn't matter. For Entity Framework, I use a in-memory SQLite database in other projects (connection string `DataSource={Guid.NewGuid()};mode=memory;`). Maybe something equivalent works for NHibernate (https://github.com/fabmoll/NHibernateSQLite)`?

**Comment by craigfowler** [comment]
_(I work with Paul, who reported this)_

NHibernate supports SQLite out of the box in fact.  I've got a few repro cases for NHibernate issues (unrelated to Plainquire), on my own personal Github profile.  They all use in-memory SQLite DBs.  Feel free to pillage some of the setup logic from any of those if you'd like to use it as inspiration to scaffold tests.  Unfortunately I'm about to go on vacation and I'm not going to get time to write a test case myself before I go.

**Comment by fschick** [comment]
Final release is here [6.0.0](https://github.com/plainquire/plainquire/releases/tag/6.0.0). Can this issue be closed?

**Comment by paul-aylett** [comment]
Sorry for delayed response. Thank you very much for this enhancement.
