### ISSUE TITLE
Swagger specification is obscured

### ISSUE THREAD

**Issue by kerajel** [fschick/FilterExpressionCreator#5]
I will break the problem down into 3 points:

1) It is impossible to determine whether a specific endpoint uses EntityFilter and thus conditional syntax is applicable. A consumer might be confused and could try to use the syntax on endpoints which do not use EntityFilter. Maybe it is possible to add a specific visual flag?

2) It is impossible to guess target property type since everything is string. Maybe it could be possible to have some highlight that would indicate the actual property type?

3) Enums are not available via dropdown lists unlike traditional body filters. Since conditional string expressions are used, we can't have the same dropdown, but maybe it is possible to still have dropdown somewhere near as a reference?

**Comment by fschick** [comment]
You have to distinguish between OpenAPI (formerly Swagger) UI and specification. From the demo: [UI](https://filterexpressioncreator.schick-software.de/openapi/index.html) and [specification](https://filterexpressioncreator.schick-software.de/openapi/v1/openapi.json).

What this library does is to extend the specification. The OpenAPI UI is not part of this library and is not processed by it.

What I can do is to enrich the specification with extended attributes `x-entity-filter-*`:
```json
{
  "...": "...",
  "paths": {
    "/api/v1/Freelancer/GetFreelancers": {
      "get": {
        "...": "...",
        "parameters": [{
            "name": "id",
            "...": "...",
            "x-entity-filter-property-type": "Guid"
          }, {
            "name": "gender",
            "...": "...",
            "x-entity-filter-property-type": "Gender"
          }
        ],
        "...": "...",
        "x-entity-filter-has-filters": true
      }
    },
  },
  "components": {
    "schemas": {
	  "...": "...",
      "Gender": {
        "enum": [
          "Divers",
          "Male",
          "Female"
        ],
        "type": "string",
        "description": "Gender enum"
      },
      "...": "..."
    }
  }
}
```

Afterwards you can adjust the UI in your project e.g. by display extensions or [inject custom css](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#inject-custom-css).
```csharp
.UseSwaggerUI(options => options.ShowExtensions());
```

Would this help?

**Comment by kerajel** [comment]
Yes, I think that would work and will be very appreciated!

**Comment by fschick** [comment]
Done, release [4.4.0](https://github.com/fschick/FilterExpressionCreator/releases/tag/4.4.0)

**Comment by kerajel** [comment]
![image](https://user-images.githubusercontent.com/10383379/222697867-db6630e6-166c-4268-b06e-5db0ea291d65.png)

I have updated the package and added the following line ```app.UseSwaggerUI(x => x.ShowExtensions());``` but I don't see any difference

**Comment by fschick** [comment]
Did you registered all required extensions?
```csharp
builder.Services
    .AddControllers()
    .AddFilterExpressionsSupport(); // <== REQUIRED
...
builder.Services.AddSwaggerGen(options =>
    options.AddFilterExpressionsSupport() // <== REQUIRED
);
...
app.UseSwaggerUI(o =>
    o.ShowExtensions() // <== REQUIRED
);
```
I created a demo project with all necessary stuff: [FS.FilterExpressionCreator.Test.zip](https://github.com/fschick/FilterExpressionCreator/files/10883933/FS.FilterExpressionCreator.Test.zip)

![grafik](https://user-images.githubusercontent.com/7911094/222768981-dc3e2f20-4c56-45df-ba23-fb9f7b9541f1.png)

**Comment by kerajel** [comment]
While it indeed works in your project, in my real application there was no metadata present. I went to comment out everything in my Program.cs leaving only code from your example and then it worked. Something must be conflicting, I'll write back once I figure out what's causing it.

Thanks for the feature!
