### ISSUE TITLE
Empty input query parameters translated to empty string instead of null and not considered as empty

### ISSUE THREAD

**Issue by xakpc** [fschick/FilterExpressionCreator#8]
Hello,

I found a problem with the binding of empty parameters in the filter

I have a Razor Pages application

    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>

I have a page that accepts GET requests from htmx: `Request.QueryString = "?name=abcd&&createdAt=&updatedAt="`

I found out that empty query values translated into empty strings in ValueFilters
![image](https://github.com/user-attachments/assets/6445446b-76a5-4ec4-af3c-ea6e10263fe0)

This makes them considered as not empty (`IsEmpty == false`), but at the same time they are invalid when materialized or converted to a string

    {Unable to parse given filter value}
        Configuration: {Plainquire.Filter.Abstractions.FilterConfiguration}

Apparently, this is by design, when binding is done `ValueProviderResult.FirstValue` will return an empty string if the query parameter is present but has no value. 

Looks like the solution might be to explicitly set them as null in [the binder](https://github.com/plainquire/plainquire/blob/34aa6557946d63cbb76789383c592fe0f0ba67a7/Plainquire.Filter/Plainquire.Filter.Mvc/ModelBinders/EntityFilterModelBinder.cs#L34C33-L34C34) or change `IsEmpty` [property of](https://github.com/plainquire/plainquire/blob/34aa6557946d63cbb76789383c592fe0f0ba67a7/Plainquire.Filter/Plainquire.Filter/Filters/ValueFilter.cs#L30C90-L30C98) `ValueFilter` to check for `string.IsNullOrEmpty`.

I would be glad to provide a pull-request of the preferred solution because right now an annoying workaround is to check and remove all filter properties if they are empty strings.

**Comment by fschick** [comment]
It's by design to be able to filter for an empty string (`""` /  `string.Empty`). Maybe it would be useful to have the possibility to configure or intercept the binding. I'll have a look later today.

**Comment by fschick** [comment]
As I wrote earlier it's by design to be able to filter for string.Empty. If you like not to filter for a value, omit it. I've [documented this behavior](https://github.com/plainquire/plainquire?tab=readme-ov-file#filter-by---stringempty) and don't like to change it without in-depth thinking.

I think the best solution for you would be to write an interceptor and register / use it by:

```csharp
// Register is global
IFilterInterceptor.Default = new OmitWhenEmptyFilterInterceptor();

// Or using it from dependency injection / factory / manually by
var interceptor  = new OmitWhenEmptyFilterInterceptor();

var filterWithoutEmptyValues = freelancerFilter.CreateFilter(interceptor);
var query = _dbContext
    .Set<Freelancer>()
    .Where(filterWithoutEmptyValues);
```

```csharp
public class OmitWhenEmptyFilterInterceptor : IFilterInterceptor
{
    public Expression<Func<TEntity, bool>>? CreatePropertyFilter<TEntity>(PropertyInfo propertyInfo, ValueFilter[] filters, FilterConfiguration configuration)
    {
        filters = [.. filters.Where(ValueIsNotNullOrEmpty)];
        if (filters.Length == 0)
            // return expression to 'true' because return null is interpreted as 'do the default'
            return x => true;

        var propertySelector = typeof(TEntity).CreatePropertySelector(propertyInfo.Name);
        return PropertyFilterExpression.CreateFilter<TEntity>(propertyInfo.PropertyType, propertySelector, filters, configuration, this);
    }

    private static bool ValueIsNotNullOrEmpty(ValueFilter valueFilter)
         => !string.IsNullOrEmpty(valueFilter.Value);

    Func<DateTimeOffset> IFilterInterceptor.Now => () => DateTimeOffset.Now;
}
```

Would this be an acceptable solution for you?

**Comment by xakpc** [comment]
Thanks!

I tested your interceptor and it works fine, yeah it's absolutely acceptable. 
I thought about using interceptor myself but did not figure out how it was supposed to work

**Comment by fschick** [comment]
Interceptors are not yet as well designed as I would like them to be. I've added some convenience methods. Are you willing to update to 5.1.0 and replace the interceptor to prevent breaking changes in futures?

```csharp
public class OmitEmptyFilterInterceptor : IFilterInterceptor
{
    public Expression<Func<TEntity, bool>>? CreatePropertyFilter<TEntity>(PropertyInfo propertyInfo, IEnumerable<ValueFilter> filters, FilterConfiguration configuration)
    {
        var nonEmptyFilters = filters.Where(ValueIsNotNullOrEmpty).ToList();

        var noFilterRequired = nonEmptyFilters.Count == 0;
        return noFilterRequired
            ? PropertyFilterExpression.EmptyFilter<TEntity>()
            : PropertyFilterExpression.CreateFilter<TEntity>(propertyInfo, nonEmptyFilters, configuration, this);
    }

    private static bool ValueIsNotNullOrEmpty(ValueFilter valueFilter)
        => !string.IsNullOrEmpty(valueFilter.Value);

    Func<DateTimeOffset> IFilterInterceptor.Now => () => DateTimeOffset.Now;
}
```

I've added this interceptor as [sample](https://github.com/plainquire/plainquire?tab=readme-ov-file#sample-interceptor) in documentation.
