### ISSUE TITLE
EntityPage could not be bound as property in RazorPages

### ISSUE THREAD

**Issue by xakpc** [fschick/FilterExpressionCreator#9]
Hello, 

I found an issue when using `EntityPage` in `RazorPages` as a property

Some context: 
`dotnet 8, Razor Pages`

I use property binding for filters and sorting to use it in different handlers and it works perfectly fine
```c#
public class IndexModel : PageModel
{    
    [FromQuery]
    public EntityFilter<ListView> Filter { get; set; } = new ();

    [FromQuery(Name="orderBy")]
    public EntitySort<ListView> Sort { get; set; } = new();

    // ...
}
```

But when I add pagination

```c#
    [FromQuery(Name = "pn")]
    public EntityPage Pagination { get; set; } = new (1, 5);
```

I have an exception

```
InvalidOperationException: Unable to get original parameter name.
Plainquire.Page.Mvc.ModelBinders.EntityPageModelBinder.BindModelAsync(ModelBindingContext bindingContext)
```

After I checked the code I found that it [requires parameter name](https://github.com/plainquire/plainquire/blob/73c83991883a5ac4168ac80e4fb91cfb8e140434/Plainquire.Page/Plainquire.Page.Mvc/ModelBinders/EntityPageModelBinder.cs#L34) which make property binding unusable (it does not have parameter name). 

IMO it would be convenient to support it, for cases when there are several handlers and you need to use table state in all of them. It looks like using `ModelBindingContext.OriginalModelName` instead of `ModelBindingContext.ModelMetadata.ParameterName` should cover both cases.

WDYT?

Br,
Pavel

**Comment by fschick** [comment]
If I remember right, I need the `ParameterName` to be able to remove it later from swagger UI created from MVC controller. I didn't tested Razor pages, Blazor nor minimal API. Maybe it's time to take a look at the points. I haven't worked with Razor for the last 10 years. Would you provide a minimal sample to reproduce the exception?

**Comment by xakpc** [comment]
Sure, here is a boilerplate razor page project with `EntityPage` that would fail on launch 
all relevant code is inside `Index.cshtml.cs`
[latest.zip](https://github.com/user-attachments/files/16454435/latest.zip)

**Comment by fschick** [comment]
Thank you for the sample. It helps me to understand the issue. I reviewed it and definitely want to fix it. Unfortunately, my time is limited for the next 2-3 weeks, so it will take some time.

I also accept pull requests, but the quality standards are high and there is currently no code of conduct. The code coverage is >85%, and the functional test coverage >99%.

In terms of procedure, I would first implement your suggestion with `ModelBindingContext.OriginalModelName`. Then I would see if and how you can make all unit tests pass again without losing functionality or tests. Afterwards it would still need unit tests that cover the functionality for Razor pages.

Feel free to let me know if you still want to help.

Either way, thanks for creating the issue. It helps to improve the product quality.

**Comment by fschick** [comment]
Solved with [5.2.0](https://github.com/plainquire/plainquire/releases/tag/5.2.0)

**Comment by fschick** [comment]
Do you have any further questions or can the issue be closed?

**Comment by xakpc** [comment]
Big thanks @fschick for your work! I believe it could be closed
